In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import pickle
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv("C:\Rajesh Data\Machine Learning\Datasets\student_placement.csv")

In [3]:
data

     cgpa   iq  profile_score  placed
0    5.97  106             61       0
1    6.83  113             77       0
2    6.60  110             61       0
3    5.54  113             68       0
4    6.84  102             67       0
..    ...  ...            ...     ...
295  6.44  107             54       0
296  6.09  108             52       0
297  7.68  101             70       1
298  7.00   90             28       1
299  4.79  118             70       0

[300 rows x 4 columns]

In [4]:
X = data.drop('placed', axis=1)
y = data['placed']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [7]:
scaler = StandardScaler()

In [10]:
X_train_trf = scaler.fit_transform(X=X_train)
X_test_trf = scaler.transform(X_test)

In [12]:
model = LogisticRegression()

In [13]:
model.fit(X_train, y_train)

LogisticRegression()

In [14]:
from sklearn.metrics import accuracy_score

In [15]:
pred = model.predict(X_test)

In [16]:
accuracy_score(y_test,pred)

0.9

In [17]:
pickle.dump(model, open('SSmodel.pkl', 'wb'))

In [20]:
X_test

     cgpa   iq  profile_score
294  7.18  106             61
259  5.13  114             54
255  6.34  112             54
241  8.56  102             63
176  4.60  116             71
10   7.64  102             51
122  7.71  109             50
108  7.45  108             65
115  7.30  101             50
111  5.67  112             67
273  8.13   91             35
188  6.97  101             68
52   6.56  104             77
37   6.89  103             37
23   7.76   96             62
216  6.47  108             41
79   8.41   93             78
120  7.93   95             50
61   6.24  111             69
194  7.04   96             47
298  7.00   90             28
177  6.66  105             67
236  5.86  105             43
256  7.65   98             50
270  5.51  114             51
268  7.42   98             49
133  8.21   89             51
242  7.24  113             72
295  6.44  107             54
252  6.88   94             71
107  6.89  105             76
85   6.86  106             59
264  7.12   96             54
217  7.21  104             76
258  5.76  114             52
156  5.71  117             76
163  5.52  116             58
197  6.32  107             68
109  6.23  113             65
138  8.80   83             62
105  7.35   93             45
221  8.25   96             57
90   7.63   91             79
38   6.79   92             73
125  6.27  110             38
113  8.25   92             67
58   7.70  103             56
248  5.94  101             38
175  6.40  105             55
73   5.52  107             78
6    7.40  100             71
97   7.32  101             69
49   7.65   94             87
98   7.27   91             70
283  8.35   96             89
211  5.64  110             51
41   6.05  106             94
147  8.11   93             72
35   5.50  112             54
13   7.74   96             72

In [22]:
model.predict(np.array([8.56,102,63]).reshape(1,3))

array([1], dtype=int64)